import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Hero from "~/Components/Hero";
import { Leistungen } from "~/Components/Leistungen";
import Navbar from "~/Components/Navbar";
import werbung from "~/../public/steiner_werbung.png";
import test1 from "~/../public/cov.jpg";
import test2 from "~/../public/sean-pollock-PhYq704ffdA-unsplash.jpg";
import test3 from "~/../public/cdc-c4IBsSCuwIU-unsplash.jpg";
import test4 from "~/../public/collin-8FxJi5wuwKc-unsplash.jpg";
import Footer from "~/Components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="">
        <Hero />
      </main>

      <Leistungen />
      <section className="h-[30rem]">
        <div className="container mx-auto flex flex-col gap-8 px-8 md:relative">
          <Image
            src={werbung}
            alt=""
            className="inset-0 overflow-hidden rounded-md md:absolute"
          />
          <div className="right-0 md:absolute xl:top-20 2xl:right-52">
            <div className="card w-full bg-primary shadow-xl">
              <div className="card-body">
                <h2 className="card-title">Wir sind da, wo sie uns brauchen</h2>
                <p>Wir halten ihr Unternehmen sicher </p>
                <p>Rund um die Uhr für sie da!</p>
                <div className="card-actions justify-end">
                  <button className="btn-info btn shadow-xl">
                    Jetzt Anfragen
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-4">
        <h1 className="mb-2 text-center text-4xl">Unsere Arbeit</h1>
        <Carousel />
      </section>
      <Footer />
    </>
  );
};

function Carousel() {
  return (
    <div className="carousel mx-auto h-96 w-3/4 rounded-lg">
      <div id="slide1" className="carousel-item relative w-full">
        <Image src={test1} alt="" className="mx-auto md:w-1/2 rounded-lg " />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide4" className="btn-circle btn">
            ❮
          </a>
          <a href="#slide2" className="btn-circle btn">
            ❯
          </a>
        </div>
      </div>
      <div id="slide2" className="carousel-item relative w-full">
        <Image src={test2} alt="" className="mx-auto w-fit rounded-lg" />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide1" className="btn-circle btn">
            ❮
          </a>
          <a href="#slide3" className="btn-circle btn">
            ❯
          </a>
        </div>
      </div>
      <div id="slide3" className="carousel-item relative w-full">
        <Image src={test4} alt="" className="mx-auto w-fit rounded-lg" />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide2" className="btn-circle btn">
            ❮
          </a>
          <a href="#slide4" className="btn-circle btn">
            ❯
          </a>
        </div>
      </div>
      <div id="slide4" className="carousel-item relative w-full">
        <Image src={test3} alt="" className="mx-auto w-fit rounded-lg" />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide3" className="btn-circle btn">
            ❮
          </a>
          <a href="#slide1" className="btn-circle btn">
            ❯
          </a>
        </div>
      </div>
    </div>
  );
}

export default Home;
